# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Portfolio Site
email: hahnandy0201@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A place to share my work and developer portfolio. Feel free to reach out 
  through my email!
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "https://hahnandrew.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: andrewh04116643
github_username:  hahnandrew
linkedin_username: andrew-hahn-986a3a157

header_pages:
  - about.md
  - hello.md
  - portfolio.md

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
